// import 'package:ai_chat_bot/views/new_chatscreen.dart';
// import 'package:flutter/material.dart';
// import 'package:provider/provider.dart';
// import 'package:firebase_core/firebase_core.dart'; // 👈 Firebase core import
// import 'viewmodels/chat_viewmodel.dart';
// import 'views/chat_screen.dart';

// Future<void> main() async {
//   WidgetsFlutterBinding.ensureInitialized();

//   // 👇 Initialize Firebase
//   await Firebase.initializeApp();

//   runApp(
//     ChangeNotifierProvider(
//       create: (_) => ChatViewModel(),
//       child: const MyApp(),
//     ),
//   );
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       debugShowCheckedModeBanner: false,
//       title: "Gemini AI ChatBot",
//       theme: ThemeData(useMaterial3: true),
//       home: ChatScreen(),
//     );
//   }
// }


// lib/main.dart
import 'package:ai_chat_bot/views/new_chatscreen.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'viewmodels/chat_viewmodel.dart';
import 'views/chat_screen.dart';
 // generated by flutterfire configure

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
   
  );

  runApp(
    ChangeNotifierProvider(
      create: (_) => ChatViewModel(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Gemini AI ChatBot',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: const ChatScreen(),
    );
  }
}

